import { Theme } from './types.js';

export const themes: { [key: string]: Theme } = {
    default: {
        titleColor: '#41b883',
        textColor: '#41b883',
        iconColor: '#41b883',
        bgColor: '#273849',
        borderColor: '#415367',
    },
    dark: {
        titleColor: '#70a5fd',
        textColor: '#ffffff',
        iconColor: '#79ff97',
        bgColor: '#151515',
        borderColor: '#1f1f1f',
    },
    radical: {
        titleColor: '#fe428e',
        textColor: '#a9fef7',
        iconColor: '#f8d847',
        bgColor: '#141321',
        borderColor: '#383838',
    },
    merko: {
        titleColor: '#abd200',
        textColor: '#68b587',
        iconColor: '#b7d364',
        bgColor: '#0a0f0b',
        borderColor: '#1f1f1f',
    },
    gruvbox: {
        titleColor: '#fabd2f',
        textColor: '#8ec07c',
        iconColor: '#fe8019',
        bgColor: '#282828',
        borderColor: '#3c3836',
    },
    tokyonight: {
        titleColor: '#70a5fd',
        textColor: '#38bdae',
        iconColor: '#bf91f3',
        bgColor: '#1a1b27',
        borderColor: '#1f2335',
    },
    onedark: {
        titleColor: '#e4bf7a',
        textColor: '#df6d74',
        iconColor: '#8eb573',
        bgColor: '#282c34',
        borderColor: '#3e4451',
    },
    cobalt: {
        titleColor: '#e683d9',
        textColor: '#ffffff',
        iconColor: '#75eeb2',
        bgColor: '#193549',
        borderColor: '#1f456e',
    },
    synthwave: {
        titleColor: '#e2e9ec',
        textColor: '#e5289e',
        iconColor: '#ef8539',
        bgColor: '#2b213a',
        borderColor: '#6b4d8a',
    },
    highcontrast: {
        titleColor: '#e7f216',
        textColor: '#ffffff',
        iconColor: '#00ffff',
        bgColor: '#000000',
        borderColor: '#ffffff',
    },
    dracula: {
        titleColor: '#ff6e96',
        textColor: '#f8f8f2',
        iconColor: '#79dafa',
        bgColor: '#282a36',
        borderColor: '#44475a',
    },
    prussian: {
        titleColor: '#bddfff',
        textColor: '#6e9ed8',
        iconColor: '#38a0ff',
        bgColor: '#172f45',
        borderColor: '#255078',
    },
    monokai: {
        titleColor: '#eb1f6a',
        textColor: '#f1f1eb',
        iconColor: '#e28905',
        bgColor: '#272822',
        borderColor: '#4e4e43',
    },
    vue: {
        titleColor: '#41b883',
        textColor: '#41b883',
        iconColor: '#41b883',
        bgColor: '#273849',
        borderColor: '#415367',
    },
    'vue-dark': {
        titleColor: '#41b883',
        textColor: '#fffefe',
        iconColor: '#41b883',
        bgColor: '#0d1117',
        borderColor: '#1f2328',
    },
    'shades-of-purple': {
        titleColor: '#fad000',
        textColor: '#a599e9',
        iconColor: '#b362ff',
        bgColor: '#2d2b55',
        borderColor: '#4d21fc',
    },
    nightowl: {
        titleColor: '#c792ea',
        textColor: '#7fdbca',
        iconColor: '#ffeb95',
        bgColor: '#011627',
        borderColor: '#1d3b53',
    },
    'buefy-dark': {
        titleColor: '#7957d5',
        textColor: '#c3c3c3',
        iconColor: '#ff3860',
        bgColor: '#1d1e22',
        borderColor: '#363636',
    },
    'blue-green': {
        titleColor: '#2f97c1',
        textColor: '#0cf57d',
        iconColor: '#00d8ff',
        bgColor: '#040f0f',
        borderColor: '#0f4c59',
    },
    algolia: {
        titleColor: '#00aeff',
        textColor: '#ffffff',
        iconColor: '#00aeff',
        bgColor: '#050f2c',
        borderColor: '#172a53',
    },
    'great-gatsby': {
        titleColor: '#ffa726',
        textColor: '#ffd95b',
        iconColor: '#ffa726',
        bgColor: '#000000',
        borderColor: '#684c8d',
    },
    darcula: {
        titleColor: '#ba5dd0',
        textColor: '#bcbec4',
        iconColor: '#6b9cef',
        bgColor: '#242424',
        borderColor: '#323232',
    },
    bear: {
        titleColor: '#e03c8a',
        textColor: '#bcb28d',
        iconColor: '#00aeff',
        bgColor: '#1f2023',
        borderColor: '#36373a',
    },
    'solarized-dark': {
        titleColor: '#268bd2',
        textColor: '#859900',
        iconColor: '#b58900',
        bgColor: '#002b36',
        borderColor: '#073642',
    },
    'solarized-light': {
        titleColor: '#268bd2',
        textColor: '#859900',
        iconColor: '#b58900',
        bgColor: '#fdf6e3',
        borderColor: '#eee8d5',
    },
    'chartreuse-dark': {
        titleColor: '#7fff00',
        textColor: '#fff',
        iconColor: '#00aeff',
        bgColor: '#000',
        borderColor: '#1f1f1f',
    },
    nord: {
        titleColor: '#81a1c1',
        textColor: '#d8dee9',
        iconColor: '#88c0d0',
        bgColor: '#2e3440',
        borderColor: '#3b4252',
    },
    gotham: {
        titleColor: '#2aa889',
        textColor: '#99d1ce',
        iconColor: '#599cab',
        bgColor: '#0c1014',
        borderColor: '#1d252d',
    },
    'material-palenight': {
        titleColor: '#c792ea',
        textColor: '#a6accd',
        iconColor: '#89ddff',
        bgColor: '#292d3e',
        borderColor: '#444267',
    },
    graywhite: {
        titleColor: '#24292e',
        textColor: '#24292e',
        iconColor: '#24292e',
        bgColor: '#ffffff',
        borderColor: '#e1e4e8',
    },
    'vision-friendly-dark': {
        titleColor: '#ffb000',
        textColor: '#ffffff',
        iconColor: '#785ef0',
        bgColor: '#000000',
        borderColor: '#1f1f1f',
    },
    'ayu-mirage': {
        titleColor: '#f4cd7c',
        textColor: '#73d0ff',
        iconColor: '#ffcc66',
        bgColor: '#1f2430',
        borderColor: '#2c3444',
    },
    'midnight-purple': {
        titleColor: '#9745f5',
        textColor: '#ffffff',
        iconColor: '#8b7ec9',
        bgColor: '#000000',
        borderColor: '#1f1f1f',
    },
    calm: {
        titleColor: '#e07a5f',
        textColor: '#ebcfb2',
        iconColor: '#edae49',
        bgColor: '#1a1a1a',
        borderColor: '#2a2a2a',
    },
    'flag-india': {
        titleColor: '#ff8f1c',
        textColor: '#250E62',
        iconColor: '#509E2F',
        bgColor: '#ffffff',
        borderColor: '#e1e4e8',
    },
    omni: {
        titleColor: '#FF79C6',
        textColor: '#E1E1E6',
        iconColor: '#E89E64',
        bgColor: '#191622',
        borderColor: '#44475a',
    },
    react: {
        titleColor: '#61dafb',
        textColor: '#ffffff',
        iconColor: '#61dafb',
        bgColor: '#20232a',
        borderColor: '#2d3748',
    },
    jolly: {
        titleColor: '#ff64da',
        textColor: '#ffffff',
        iconColor: '#a960ff',
        bgColor: '#291B3E',
        borderColor: '#461e5b',
    },
    maroongold: {
        titleColor: '#F7EF8A',
        textColor: '#E0AA3E',
        iconColor: '#F7EF8A',
        bgColor: '#260000',
        borderColor: '#3d0000',
    },
    yeblu: {
        titleColor: '#ffff00',
        textColor: '#ffffff',
        iconColor: '#0000ff',
        bgColor: '#002046',
        borderColor: '#19558c',
    },
    blueberry: {
        titleColor: '#82aaff',
        textColor: '#e4f0fb',
        iconColor: '#89ddff',
        bgColor: '#242938',
        borderColor: '#3e4b66',
    },
    slateorange: {
        titleColor: '#e2a75a',
        textColor: '#ffffff',
        iconColor: '#e2a75a',
        bgColor: '#36393f',
        borderColor: '#4a4d52',
    },
    kacho_ga: {
        titleColor: '#bf4a3f',
        textColor: '#d9c8a9',
        iconColor: '#a64833',
        bgColor: '#402b23',
        borderColor: '#ae9a87',
    },
    outrun: {
        titleColor: '#ffcc00',
        textColor: '#8b9fde',
        iconColor: '#ff1aff',
        bgColor: '#141439',
        borderColor: '#1f1f5e',
    },
    ocean_dark: {
        titleColor: '#8957B2',
        textColor: '#92D534',
        iconColor: '#519259',
        bgColor: '#151a28',
        borderColor: '#1d2633',
    },
    city_lights: {
        titleColor: '#5D8CB3',
        textColor: '#B7C9D3',
        iconColor: '#4BC96B',
        bgColor: '#1D252C',
        borderColor: '#354856',
    },
    github_dark: {
        titleColor: '#58a6ff',
        textColor: '#c9d1d9',
        iconColor: '#79c0ff',
        bgColor: '#0d1117',
        borderColor: '#30363d',
    },
    discord_old_blurple: {
        titleColor: '#7289da',
        textColor: '#ffffff',
        iconColor: '#7289da',
        bgColor: '#2c2f33',
        borderColor: '#23272a',
    },
    aura_dark: {
        titleColor: '#a277ff',
        textColor: '#edecee',
        iconColor: '#61ffca',
        bgColor: '#15141b',
        borderColor: '#3d375e',
    },
    panda: {
        titleColor: '#19f9d8',
        textColor: '#FF75B5',
        iconColor: '#ffb86c',
        bgColor: '#31353a',
        borderColor: '#4a4d52',
    },
    noctis_minimus: {
        titleColor: '#d3b692',
        textColor: '#c5cdd3',
        iconColor: '#7aa5ff',
        bgColor: '#1b2932',
        borderColor: '#273645',
    },
    cobalt2: {
        titleColor: '#ffc600',
        textColor: '#ffffff',
        iconColor: '#80ffbb',
        bgColor: '#193549',
        borderColor: '#285580',
    },
    swift: {
        titleColor: '#f05237',
        textColor: '#ffffff',
        iconColor: '#f05237',
        bgColor: '#232323',
        borderColor: '#3a3a3a',
    },
    aura: {
        titleColor: '#a277ff',
        textColor: '#edecee',
        iconColor: '#61ffca',
        bgColor: '#15141b',
        borderColor: '#3d375e',
    },
    apprentice: {
        titleColor: '#ffffaf',
        textColor: '#bcbcbc',
        iconColor: '#87afd7',
        bgColor: '#262626',
        borderColor: '#3a3a3a',
    },
    moltack: {
        titleColor: '#86092C',
        textColor: '#574038',
        iconColor: '#F19D38',
        bgColor: '#F5E1C0',
        borderColor: '#E4D4B5',
    },
    codeSTACKr: {
        titleColor: '#ff652f',
        textColor: '#ffffff',
        iconColor: '#ff652f',
        bgColor: '#09131B',
        borderColor: '#0D1620',
    },
    rose_pine: {
        titleColor: '#9ccfd8',
        textColor: '#e0def4',
        iconColor: '#c4a7e7',
        bgColor: '#191724',
        borderColor: '#26233a',
    },
};

export function getTheme(themeName: string = 'default'): Theme {
    return themes[themeName] || themes.default;
}
