name: Daily Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          touch .env
          echo "GITHUB_API_URL"=https://api.github.com
          echo "GITHUB_USERNAME"=pphatdev
          echo "GITHUB_REPO"=pphatdev
          echo "STATUS_UPDATE_INTERVAL"=60
          echo "WAKA_API"=https://wakatime.com/api/v1
          echo "WAKA_USERNAME"=pphatdev
          echo "WAKA_PROJECT"=
          echo "WAKA_INTERVAL"=60
          echo "DATA_PATH"=data
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
          echo "WAKA_PROJECT=${{ secrets.WAKA_KEY }}" >> .env

          cat .env

          pip install -r requirements.txt
          pip install python-dotenv

      - name: Load environment variables
        run: |
          echo "Loading environment variables from .env"
          set -o allexport; source .env; set +o allexport

      - name: Run main.py
        run: python src/main.py