name: Daily Workflow

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cp .env.example .env
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
          echo "WAKA_TOKEN=${{ secrets.WAKA_KEY }}" >> .env
          cat .env
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Load environment variables
        run: |
          echo "Loading environment variables from .env"
          set -o allexport; source .env; set +o allexport

      - name: Run main.py
        run: python src/main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'pphatdev'
          git config --global user.email 'pphat.kits@gmail.com'
          git add .
          git commit -m "Update generated content $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
